### ISSUE TITLE
windows平台编译micro发生错误  无法解析的外部符号

### ISSUE THREAD

**Issue by a1312963** [easysoft/phpmicro#12]
![image](https://github.com/easysoft/phpmicro/assets/15373061/df8124e3-8d61-468b-ba04-c53cee0edceb)
编译7.4和8.1版本 都发生这个错误

**Comment by dixyes** [comment]
windows构建必须使用patch

见 https://github.com/easysoft/phpmicro/tree/master/patches

使用patch后彻底清空构建环境再试下

**Comment by a1312963** [comment]
patch具体命令应该怎么写

**Comment by dixyes** [comment]
> patch具体命令应该怎么写

windows下 cmd里和bash一样：
```cmd
REM 在php源码目录下
patch -p1 < path\to\patchfile
```

powershell里我不知道怎么做

顺便提一下 strawberry perl带的那个patch可能有点毛病，如果上面的命令有问题（coredump了），在php源码目录
```
git apply path\to\patchfile
```

**Comment by a1312963** [comment]
![image](https://github.com/easysoft/phpmicro/assets/15373061/e82f3c1a-0562-406a-930b-221c6a6e215f)
pdo_sqlite curl xml部分扩展会出现这个链接错误 应该怎么解决呢

**Comment by dixyes** [comment]
@a1312963 你需要自己构建几乎所有依赖 php官方给的大多数扩展都是动态编译的 并不能链接进去 (8.x的libcurl好像是变成静态的了)

**Comment by dixyes** [comment]
至于curl如何构建 可以参考 https://github.com/dixyes/lwmbs/blob/master/windows/libraries/curl.php

**Comment by a1312963** [comment]
是能用这个项目来编译lib吗 还是需要自己下载对应源码编译静态的lib

**Comment by dixyes** [comment]
> 
lwmbs可以单独构建库: https://github.com/dixyes/lwmbs/blob/master/build_libs.php

micro和lwmbs都不支持7.4了 你要自己移植micro到7.4 这只是给你个构建libcurl的命令的参考

**Comment by a1312963** [comment]
能提供一下windows php8.1版本的patch文件吗

**Comment by dixyes** [comment]
> 能提供一下windows php8.1版本的patch文件吗

用版本号小于它的最新的patch
例如 现在有73 80 82三个版本 则 73 74 用73， 80 81 用 80， 82 83用82

**Comment by a1312963** [comment]
![image](https://github.com/easysoft/phpmicro/assets/15373061/c47313e8-9024-4436-bb4c-21eb16ded26b)
micro 是否支持opcache呢 micro编译后无生成opcache的dll 通过ini开启也无法使用这个模块

**Comment by dixyes** [comment]
> ![image](https://user-images.githubusercontent.com/15373061/258275087-c47313e8-9024-4436-bb4c-21eb16ded26b.png) micro 是否支持opcache呢 micro编译后无生成opcache的dll 通过ini开启也无法使用这个模块

https://github.com/easysoft/phpmicro/blob/master/patches/static_opcache_83.patch

**Comment by a1312963** [comment]
![image](https://github.com/easysoft/phpmicro/assets/15373061/d7782dec-a0a8-4eaa-906c-e97081294ef7)
![image](https://github.com/easysoft/phpmicro/assets/15373061/67c0c50c-7003-48c0-8f09-6d0fc5a92601)
打了patch之后可以使用opcache等函数了 但打印phpinfo里面的信息 似乎是不支持的

**Comment by dixyes** [comment]
> ![image](https://user-images.githubusercontent.com/15373061/258283010-d7782dec-a0a8-4eaa-906c-e97081294ef7.png) ![image](https://user-images.githubusercontent.com/15373061/258283224-67c0c50c-7003-48c0-8f09-6d0fc5a92601.png) 打了patch之后可以使用opcache等函数了 但打印phpinfo里面的信息 似乎是不支持的

本来它就只支持这些短生命周期sapi啊 cli是不支持的 而且cli下支持了也并不会有什么用 唯一有用的是jit 或许能提高那么一丢丢性能

**Comment by a1312963** [comment]
> > ![image](https://user-images.githubusercontent.com/15373061/258283010-d7782dec-a0a8-4eaa-906c-e97081294ef7.png) ![image](https://user-images.githubusercontent.com/15373061/258283224-67c0c50c-7003-48c0-8f09-6d0fc5a92601.png) 打了patch之后可以使用opcache等函数了 但打印phpinfo里面的信息 似乎是不支持的
> 
> 本来它就只支持这些短生命周期sapi啊 cli是不支持的 而且cli下支持了也并不会有什么用 唯一有用的是jit 或许能提高那么一丢丢性能

好的 明白了
