### ISSUE TITLE
使用 upx 减小 micro.sfx 体积时，三次压缩的体积大小在一些特定情况下会不一致

### ISSUE THREAD

**Issue by crazywhalecc** [easysoft/phpmicro#17]
https://github.com/easysoft/phpmicro/blob/e142401ee260c128ac9d6bb1e35f80040614437c/Makefile.frag#L11C1-L23C30

相关 Issue：
https://github.com/crazywhalecc/static-php-cli/issues/425

主要是修改 strip 命令，在 strip 后立刻执行 upx 压缩。但即使三次压缩体积貌似也不太一样，或者这种情况就只能再加一次构建吗

**Comment by crazywhalecc** [comment]
这个问题似乎和 upx 有关。因为 phpmicro 的原理仔细阅读了下源码就是将自身文件大小写到自身文件内，而 upx 机制是压缩，有可能一个 bit 的变化都会影响最终压缩的大小。

极端情况就是某个二进制文件大小（如 12345678 字节）压缩后可能是 x 大小，获取到压缩后的 x 大小后，第二次写入 x 大小的二进制压缩后又可能是 y 大小，以此往复，无法构建正常的 micro.sfx。

如果 micro.sfx 不更改原理的话，这个问题似乎是无解的，先关了。

**Comment by dixyes** [comment]
我有个想法来解决这个问题（顺便安排下数字签名兼容）

但人太懒了一直没做完。。。

**Comment by crazywhalecc** [comment]
> 我有个想法来解决这个问题（顺便安排下数字签名兼容）

说来听听？

**Comment by dixyes** [comment]
完整的PE/COFF ELF Mach-O editor呗

总共有以下工作量：
- [x] PE/COFF header parser/builder
- [ ] Win32 RSRC parser/builder
- [ ] ELF parser/builder
- [ ] Mach-O parser/builder
- [ ] UI (CLI/GUI)
- [ ] 交付（glci 数字签名 osscdn）

用php写的 目前我的进度如上

但我目前还有十个甚至九个要填的坑（硬件、操作系统方向），就暂且咕了，如果你有兴趣的话 我抽空发一下一起填

**Comment by dixyes** [comment]
> 完整的PE/COFF ELF Mach-O editor呗

其实还有个点 就是如果我们有了这个，就可以把phar丢进一个正经section里了，micro也不需要多次构建来固定长度了

**Comment by crazywhalecc** [comment]
这样其实相当于改了micro的运行机制吧，会和旧的胶水模式兼容吗

**Comment by dixyes** [comment]
> 这样其实相当于改了micro的运行机制吧，会和旧的胶水模式兼容吗

当前的micro是在unix下直接硬编码的offset到rodata，windows下用的Win32资源

sfx-editor的思路是扒出来这个offset来修改

对于Windows PE来说，要upx就先把sfx upx下，然后用sfx-editor修正rsrc段的offset就完事，

对于unix ELF/Mach-O来说 要支持upx就可能要新建一个section，sfx进行upx之后再附加上这个段，然后改micro源码去读这个段。

以上这么个玩法是不会改运行机制的，无非ELF/Mach-O需要改micro代码，Windows现在用这个就可以没啥问题的兼容了

WIP: https://github.com/dixyes/sfx-editor

对于数字签名：windows下你merge完sfx和payload直接签就完事了，需要自定义stub（windows这边签名是放在exe结尾的，所以需要避免php解释器去读文件结尾）晚点看能不能实现一个payload limit，这样就不需要自定义stub了

macos需要研究下

upx+签名太抽象了 暂且还没想明白，但感觉问题不大
