### ISSUE TITLE
有办法让其支持sg14扩展 或者  swoole loader 之类的扩展吗

### ISSUE THREAD

**Issue by TNT-ma** [easysoft/phpmicro#9]
我使用魔法头让其加载扩展都被提示：不支持加载动态库🥲

现在是鱼与熊掌不可兼得

用micro 就无法使用一些第三方的so扩展

**Comment by dixyes** [comment]
你用了`--enable-micro=all-static`吗 静态的micro不能加载动态库，这是c库设计决定的，你要用动态的才行

**Comment by TNT-ma** [comment]
> 你用了`--enable-micro=all-static`吗 静态的micro不能加载动态库，这是c库设计决定的，你要用动态的才行

动态的 PHPmicro 和 静态 PHPmicro  都可以单个二进制文件形式运行起来PHP环境吗？

**Comment by dixyes** [comment]
都可以正常以micro的模式运行（执行自己的payload）区别是：

- 动态的需要同版本或更高版本c库，静态的可以直接在linux内核上跑
- 动态的支持dl ffi和extension=，静态的不支持

**Comment by TNT-ma** [comment]
> 都可以正常以micro的模式运行（执行自己的payload）区别是：
> 
> * 动态的需要同版本或更高版本c库，静态的可以直接在linux内核上跑
> * 动态的支持dl ffi和extension=，静态的不支持

有没有micro  下的开发自定义扩展例子或者文档？ 我想把一个开源的https://github.com/TNT-ma/tonyenc  扩展弄到静态PHP内（micro下使用）

**Comment by dixyes** [comment]
> > 都可以正常以micro的模式运行（执行自己的payload）区别是：
> > 
> > * 动态的需要同版本或更高版本c库，静态的可以直接在linux内核上跑
> > * 动态的支持dl ffi和extension=，静态的不支持
> 
> 有没有micro 下的开发自定义扩展例子或者文档？ 我想把一个开源的https://github.com/TNT-ma/tonyenc 扩展弄到静态PHP内（micro下使用）

https://docs.toast.run/micro/chs/how-to-add-an-extension-into-micro.sfx.html
